### PR TITLE
Updating documentation

### PR DESCRIPTION
**Pull request by rompik**
To simplify support of multiple language documentation, I offer to move folder screenshots to root level of docs, and it will keep all screenshots for different language in one place. In this case, we will need to make only 1 image for all languages. 

image

In case when image contains specific language text (Chinese, English,...) we can add code language to the end of image file name, e.g.:

image

 With this naming convention, during updating of documention will be easier to control if image is missing for any language. 

Subfolders hierarchy inside folder **screenshots** will repeat subfolder hierarchy inside of languages (in this case, we need to have the same hierarchy of language's subfolders). For MD pages which have links to images, I created dedicated folders with name of MD files inside screenshots in dedicated subfolders: 
Language: 
   - admin
   - design
   -- common
   -- equipment
   -- piping
   -- structure 
   - catalogue
   - installation
   -- windows
   - development
   -- plugins              -> dedicated subfolder for file **plugins.md** inside of folder **en/development/**

I hope it will help to support multilanguage documentations and may be later to automatize translation of new md pages.

### CODE REVIEW

**Comment by eryar** [comment]
Move folder screenshots to root level of docs is GOOD, and I think folder name images better than screenshots.

In order to generate PDF automatically, all images should in images folder directly, if in sub folder will failed.
So I suggest to add the sub folder name to image name, such as admin_project_info.png.

One MD file will generate one PDF file. 

I am writing user guide Chinese version this week, after finish it I will check folders in docs for English version.

**Comment by rompik** [comment]
OK, good point regarding images folder, I will update documentation. Also, I will change names of images. I just a little doubt regarding put all images inside one folder. In future when images can be thousands, will be difficult to navigate to find proper image. Windows also has slowness of performance in case of thousands files inside one folder. But currently lets got the way which you proposed to save time for getting pdf documentation. You can write all documentation on Chinese and I can translate using Google translator to English as translation looks quite human w/out serious mistakes.

**Comment by eryar** [comment]
OK. I will check whether support sub folders and then can keep your folders.

**Comment by eryar** [comment]
image

For images it is in the root folder and can add sub folders in images;
And image file name for different languages add a suffix, like:
- demo_en.png
- demo_zh.png

For MD files is also in root folder and for different languages add a suffix, like image file name:
- user_guide_en.md
- user_guide_zh.md

What do you think?

**Pull request merged**
