### PR TITLE
Create update.py

### PR DESCRIPTION
**Pull request by rompik**
Utility for reloading python libraries during session within UI. Updated doc for creating new_utility.

### CODE REVIEW

**Comment by rompik** [comment]
Hello Shing, 
Please can you note that Russian translation file was done by a guy who called himself NeuroFreak. He is also monitoring your project's progress and tested PipeCAD to see if can propose to his management possibility of using it to replace E3D in future.

**Comment by eryar** [comment]
Hello Roman,

That's great! Thank you!

I'm taking a vacation for Chinese New Year! 

This year I will consider to use PostgreSQL database to replace SQLite and support Linux OS.

**Comment by rompik** [comment]
Hello Shing,
新年快乐 :) Hope machine translation is close to human Chinese! Take your time with family to enjoy vacation!

**Comment by eryar** [comment]
Thank you!

**Pull request merged**
